import { Trade } from './types'

export const demoTrades: Trade[] = [
  {
    id: 'demo-1',
    date: '2026-06-02',
    time: '09:15',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 450,
    risk: 150,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Bullish breakout above key resistance with strong volume confirmation. Clean structure.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Perfect execution. Let the trade run to full TP.',
    createdAt: '2026-06-02T09:15:00Z',
  },
  {
    id: 'demo-2',
    date: '2026-06-03',
    time: '10:30',
    symbol: 'NQ',
    type: 'Long',
    pnl: -200,
    risk: 200,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Tried to catch a bounce at support but entered without waiting for confirmation.',
    followedRules: false,
    touchedAfterEntry: true,
    notes: 'Entered too early. Should have waited for the confirmation candle.',
    createdAt: '2026-06-03T10:30:00Z',
  },
  {
    id: 'demo-3',
    date: '2026-06-04',
    time: '14:20',
    symbol: 'BTC',
    type: 'Long',
    pnl: 320,
    risk: 160,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Break and retest of daily resistance turned support. Clean structure with higher lows.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Good trade. Followed the plan.',
    createdAt: '2026-06-04T14:20:00Z',
  },
  {
    id: 'demo-4',
    date: '2026-06-04',
    time: '16:45',
    symbol: 'GBPUSD',
    type: 'Long',
    pnl: 150,
    risk: 75,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'London session continuation trade. Trend was clear.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Small but clean win.',
    createdAt: '2026-06-04T16:45:00Z',
  },
  {
    id: 'demo-5',
    date: '2026-06-05',
    time: '09:00',
    symbol: 'XAUUSD',
    type: 'Short',
    pnl: 280,
    risk: 140,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Bearish rejection from major resistance zone. HTF bearish bias confirmed.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Exactly as planned. No adjustments needed.',
    createdAt: '2026-06-05T09:00:00Z',
  },
  {
    id: 'demo-6',
    date: '2026-06-06',
    time: '11:15',
    symbol: 'EURUSD',
    type: 'Long',
    pnl: -180,
    risk: 180,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Revenge trade after yesterday\'s loss. No proper setup.',
    followedRules: false,
    touchedAfterEntry: true,
    notes: 'Emotional trade. Should not have entered. Classic FOMO.',
    createdAt: '2026-06-06T11:15:00Z',
  },
  {
    id: 'demo-7',
    date: '2026-06-09',
    time: '08:45',
    symbol: 'NQ',
    type: 'Short',
    pnl: 600,
    risk: 150,
    plannedRR: 4,
    actualRR: 4.0,
    status: 'Win',
    entryReason: 'Bearish divergence on 1H with rejection from weekly resistance. Premium entry.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Best trade of the month! Let it run to full target.',
    createdAt: '2026-06-09T08:45:00Z',
  },
  {
    id: 'demo-8',
    date: '2026-06-09',
    time: '14:00',
    symbol: 'BTC',
    type: 'Long',
    pnl: -240,
    risk: 120,
    plannedRR: 3,
    actualRR: -2,
    status: 'Loss',
    entryReason: 'Attempted a long after strong move up. Bad entry timing.',
    followedRules: false,
    touchedAfterEntry: false,
    notes: 'Entered without a pullback. Chased the market.',
    createdAt: '2026-06-09T14:00:00Z',
  },
  {
    id: 'demo-9',
    date: '2026-06-10',
    time: '09:30',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 210,
    risk: 105,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Demand zone bounce with bullish momentum. News catalyst aligned.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Solid setup. Clean execution.',
    createdAt: '2026-06-10T09:30:00Z',
  },
  {
    id: 'demo-10',
    date: '2026-06-10',
    time: '15:20',
    symbol: 'EURUSD',
    type: 'Short',
    pnl: 180,
    risk: 90,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Supply zone rejection after retest. Confirmation on lower timeframe.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Good setup. Followed all rules.',
    createdAt: '2026-06-10T15:20:00Z',
  },
  {
    id: 'demo-11',
    date: '2026-06-11',
    time: '10:00',
    symbol: 'BTC',
    type: 'Short',
    pnl: -150,
    risk: 150,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Bearish setup at resistance. Valid trade but stopped out on volatility spike.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Valid setup, just didn\'t work out. Part of the game.',
    createdAt: '2026-06-11T10:00:00Z',
  },
  {
    id: 'demo-12',
    date: '2026-06-12',
    time: '09:15',
    symbol: 'NQ',
    type: 'Long',
    pnl: 450,
    risk: 150,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Gap fill trade. Market opened with a gap down and showed immediate reversal.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Great gap fill trade. Perfect R:R.',
    createdAt: '2026-06-12T09:15:00Z',
  },
  {
    id: 'demo-13',
    date: '2026-06-13',
    time: '11:30',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 0,
    risk: 100,
    plannedRR: 2,
    actualRR: 0,
    status: 'Break Even',
    entryReason: 'Valid setup, moved SL to break even after initial move. Market reversed.',
    followedRules: true,
    touchedAfterEntry: true,
    notes: 'Protected capital. Good risk management.',
    createdAt: '2026-06-13T11:30:00Z',
  },
  {
    id: 'demo-14',
    date: '2026-06-16',
    time: '08:30',
    symbol: 'GBPUSD',
    type: 'Short',
    pnl: 180,
    risk: 90,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'London open short. Key level rejection with bearish momentum.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Clean setup. Good discipline.',
    createdAt: '2026-06-16T08:30:00Z',
  },
  {
    id: 'demo-15',
    date: '2026-06-17',
    time: '13:45',
    symbol: 'NQ',
    type: 'Long',
    pnl: -300,
    risk: 150,
    plannedRR: 3,
    actualRR: -2,
    status: 'Loss',
    entryReason: 'Entered during lunch hour. Low liquidity environment. No clear setup.',
    followedRules: false,
    touchedAfterEntry: true,
    notes: 'Never trade during lunch hours. Violated my own rule again.',
    createdAt: '2026-06-17T13:45:00Z',
  },
  {
    id: 'demo-16',
    date: '2026-06-17',
    time: '16:00',
    symbol: 'GBPUSD',
    type: 'Short',
    pnl: -100,
    risk: 100,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Valid setup at resistance but position sizing was too large.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Acceptable loss. Setup was valid.',
    createdAt: '2026-06-17T16:00:00Z',
  },
  {
    id: 'demo-17',
    date: '2026-06-18',
    time: '09:00',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 560,
    risk: 140,
    plannedRR: 4,
    actualRR: 4.0,
    status: 'Win',
    entryReason: 'Perfect structure setup. Break above monthly high with strong momentum.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Best XAUUSD trade this month. Let it run to full TP.',
    createdAt: '2026-06-18T09:00:00Z',
  },
  {
    id: 'demo-18',
    date: '2026-06-19',
    time: '14:30',
    symbol: 'BTC',
    type: 'Long',
    pnl: -200,
    risk: 200,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'FOMO trade during crypto pump. No technical setup.',
    followedRules: false,
    touchedAfterEntry: true,
    notes: 'Pure greed. Should have stayed away. No clear entry criteria.',
    createdAt: '2026-06-19T14:30:00Z',
  },
  {
    id: 'demo-19',
    date: '2026-06-20',
    time: '09:30',
    symbol: 'NQ',
    type: 'Short',
    pnl: 375,
    risk: 125,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Friday sell-off setup. Rejection from weekly highs. Strong bearish momentum.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Solid end-of-week trade. Clean setup.',
    createdAt: '2026-06-20T09:30:00Z',
  },
  {
    id: 'demo-20',
    date: '2026-06-23',
    time: '10:00',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 420,
    risk: 140,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Monday gap fill continuation. Strong bullish bias after weekend news.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Great start to the week.',
    createdAt: '2026-06-23T10:00:00Z',
  },
  {
    id: 'demo-21',
    date: '2026-06-24',
    time: '09:15',
    symbol: 'NQ',
    type: 'Long',
    pnl: 300,
    risk: 100,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Continuation pattern on 15M. Higher timeframe aligned bullishly.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Perfect execution. Stuck to plan.',
    createdAt: '2026-06-24T09:15:00Z',
  },
  {
    id: 'demo-22',
    date: '2026-06-24',
    time: '14:00',
    symbol: 'XAUUSD',
    type: 'Short',
    pnl: 350,
    risk: 175,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Double top pattern with bearish divergence on RSI. Clear setup.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Good afternoon session trade.',
    createdAt: '2026-06-24T14:00:00Z',
  },
  {
    id: 'demo-23',
    date: '2026-06-25',
    time: '11:00',
    symbol: 'BTC',
    type: 'Short',
    pnl: -180,
    risk: 180,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Short attempt at resistance. Market was too volatile.',
    followedRules: false,
    touchedAfterEntry: false,
    notes: 'Should have avoided this one. BTC was erratic.',
    createdAt: '2026-06-25T11:00:00Z',
  },
  {
    id: 'demo-24',
    date: '2026-06-26',
    time: '09:45',
    symbol: 'XAUUSD',
    type: 'Short',
    pnl: 280,
    risk: 140,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Supply zone rejection. HTF bearish. Clean entry on 5M confirmation.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Textbook trade.',
    createdAt: '2026-06-26T09:45:00Z',
  },
  {
    id: 'demo-25',
    date: '2026-06-27',
    time: '10:30',
    symbol: 'NQ',
    type: 'Long',
    pnl: -120,
    risk: 120,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Valid support bounce setup. Stopped out on news spike.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Clean setup, bad luck with news timing. Accept and move on.',
    createdAt: '2026-06-27T10:30:00Z',
  },
  {
    id: 'demo-26',
    date: '2026-06-30',
    time: '09:00',
    symbol: 'EURUSD',
    type: 'Long',
    pnl: 200,
    risk: 100,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Month-end rebalancing flow. Bullish setup with strong momentum.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Good month ender.',
    createdAt: '2026-06-30T09:00:00Z',
  },
  {
    id: 'demo-27',
    date: '2026-06-30',
    time: '14:30',
    symbol: 'NQ',
    type: 'Long',
    pnl: 520,
    risk: 130,
    plannedRR: 4,
    actualRR: 4.0,
    status: 'Win',
    entryReason: 'Month-end squeeze. Strong momentum with clean breakout. Let it run.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Excellent close to June. Great trade.',
    createdAt: '2026-06-30T14:30:00Z',
  },
  {
    id: 'demo-28',
    date: '2026-07-01',
    time: '09:15',
    symbol: 'XAUUSD',
    type: 'Long',
    pnl: 480,
    risk: 160,
    plannedRR: 3,
    actualRR: 3.0,
    status: 'Win',
    entryReason: 'Start of Q3. Bullish breakout above key level. Strong momentum.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Great start to July and Q3!',
    createdAt: '2026-07-01T09:15:00Z',
  },
  {
    id: 'demo-29',
    date: '2026-07-02',
    time: '11:00',
    symbol: 'NQ',
    type: 'Short',
    pnl: -200,
    risk: 200,
    plannedRR: 2,
    actualRR: -1,
    status: 'Loss',
    entryReason: 'Overtraded after big win yesterday. No clear setup visible.',
    followedRules: false,
    touchedAfterEntry: true,
    notes: 'Revenge trade mindset crept in. Must control emotions.',
    createdAt: '2026-07-02T11:00:00Z',
  },
  {
    id: 'demo-30',
    date: '2026-07-03',
    time: '09:30',
    symbol: 'BTC',
    type: 'Long',
    pnl: 320,
    risk: 160,
    plannedRR: 2,
    actualRR: 2.0,
    status: 'Win',
    entryReason: 'Strong demand zone support. Institutional buying visible on order flow.',
    followedRules: true,
    touchedAfterEntry: false,
    notes: 'Good morning trade. Stuck to the plan.',
    createdAt: '2026-07-03T09:30:00Z',
  },
]
